### ISSUE TITLE
Cannot deploy this site

### ISSUE THREAD

**Issue by djosix** [lovenery/ncuesg2016#2]
Hello, I'm trying to deploy this website, but several errors occur:
```
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
/private/tmp/dorian/ncuesg2016/src/node_modules/mongoose/lib/schema.js:505
    throw new Error('Cannot put unique index on _id');
    ^

Error: Cannot put unique index on _id
    at Schema.path (/private/tmp/dorian/ncuesg2016/src/node_modules/mongoose/lib/schema.js:505:11)
    at Schema.add (/private/tmp/dorian/ncuesg2016/src/node_modules/mongoose/lib/schema.js:364:12)
    at new Schema (/private/tmp/dorian/ncuesg2016/src/node_modules/mongoose/lib/schema.js:88:10)
    at Mongoose.Schema (/private/tmp/dorian/ncuesg2016/src/node_modules/mongoose/lib/schema.js:60:12)
    at Object.<anonymous> (/private/tmp/dorian/ncuesg2016/src/models/code.js:4:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/dorian/ncuesg2016/src/routes/team.js:6:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
error: Forever detected script exited with code: 1
```
Is it because of the node version or the database?

**Comment by lovenery** [comment]
Try using pm2. The last commit of forever.js is Nov 2, 2016.
https://github.com/Unitech/pm2

**Comment by djosix** [comment]
PM2 is great! But it still doesn't work...
It seems like part of mongoose went wrong.

**Comment by lovenery** [comment]
I think there might be some updates on mongoose or else.
Try upgrading them?

**Comment by lovenery** [comment]
It's the problem of mongoose not upgrading.
I've pushed new commit.

**Comment by djosix** [comment]
Thanks!!
